---
# list of applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

# homebrew applications
applications:
  - autojump
  - git
  - zsh
  - vim

# homebrew cask applications
cask_applications:
  - iterm2
  - 1password
  - spotify
  - sublime-text

downloads: {}